name: development

on:
  pull_request:
    types: [review_requested, ready_for_review]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Resolves dependencies
        run: npm install

      - name: Set environment
        run: cp .env.example .env

      - name: Unit tests
        run: npm run test:unit